# Generated by Django 4.2.3 on 2023-07-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_orderout_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderout',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
