# Generated by Django 4.2.3 on 2023-07-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderout_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderout',
            name='amount',
            field=models.CharField(choices=[('option1', 'Подготовка к отправке'), ('option2', 'В пути'), ('option3', 'Прибыл в пунк назначения')], max_length=50),
        ),
    ]
