# Generated by Django 4.2.3 on 2023-07-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderout_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderout',
            name='status',
            field=models.CharField(choices=[('option1', 'Подготовка к отправке'), ('option2', 'В пути'), ('option3', 'Прибыл в пунк назначения')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderout',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
