# Generated by Django 4.2.3 on 2023-07-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orderout_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderout',
            name='amount',
        ),
        migrations.AlterField(
            model_name='orderout',
            name='status',
            field=models.CharField(choices=[('Подготовка к отправке', 'Подготовка к отправке'), ('В пути', 'В пути'), ('Прибыл в пункт назначения', 'Прибыл в пункт назначения')], max_length=50),
        ),
    ]
