# Generated by Django 4.2.3 on 2023-07-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_orderout_amount_alter_orderout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderout',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
