# Generated by Django 4.2.3 on 2023-07-10 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0009_alter_orderout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderout',
            name='worker',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='worker', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
