# Generated by Django 4.2.3 on 2023-07-10 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_orderout_user_alter_orderout_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderout',
            name='worker',
        ),
    ]
