# Generated by Django 4.2.3 on 2023-07-10 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0013_orderout_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderout',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_out_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
